# This is a config for E2B sandbox template.
# You can use template ID (5srr4gzezifjny9jvqh4) or template name (vibe-nextjs-moiz-test3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-moiz-test3") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-moiz-test3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-moiz-test3')

team_id = "5971e4ca-b364-4d8f-a054-fe7b8c2e5e9c"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-moiz-test3"
template_id = "5srr4gzezifjny9jvqh4"
